name: Python test runner

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Auto run tests
    steps:
      - name: Checkout autotests 
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
        
